<?xml version="1.0"?>
<!-- ===================================================================
     SmartSort Warehouse Robot - Xacro Model
     Author: Rishabh
     Compatible with ROS2 Humbleâ€“Jazzy + Gazebo Harmonic
     =================================================================== -->

<robot name="smartsort_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ====================== -->
  <!-- Xacro Arguments        -->
  <!-- ====================== -->
  <xacro:arg name="is_ignition" default="true"/>
  <xacro:arg name="wheel_radius" default="0.1"/>
  <xacro:arg name="wheel_separation" default="0.45"/>
  <xacro:arg name="base_length" default="0.6"/>
  <xacro:arg name="base_width" default="0.4"/>
  <xacro:arg name="base_height" default="0.2"/>

  <xacro:property name="base_length" value="$(arg base_length)" />
  <xacro:property name="base_width" value="$(arg base_width)" />
  <xacro:property name="base_height" value="$(arg base_height)" />
  <xacro:property name="wheel_radius" value="$(arg wheel_radius)" />
  <xacro:property name="wheel_separation" value="$(arg wheel_separation)" />

  <!-- Include Gazebo & ROS2 Control Submodules -->
  <xacro:include filename="smartsort_gazebo.xacro"/>
  <xacro:include filename="smartsort_ros2_control.xacro"/>

  <!-- ====================== -->
  <!-- Base Link -->
  <!-- ====================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- ====================== -->
  <!-- Left Wheel -->
  <!-- ====================== -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.2 0.225 -${base_height/2}" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- ====================== -->
  <!-- Right Wheel -->
  <!-- ====================== -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.2 -0.225 -${base_height/2}" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- ====================== -->
  <!-- Caster Wheel -->
  <!-- ====================== -->
  <link name="caster">
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.0</mu>
            <mu2>0.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="0.2 0 -0.15" rpy="0 0 0"/>
  </joint>

  <!-- ====================== -->
  <!-- Arm Assembly -->
  <!-- ====================== -->
  <link name="arm_base">
    <visual>
      <geometry>
        <cylinder radius="0.08" length="0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.08" length="0.1"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base"/>
    <origin xyz="0.1 0 0.15"/>
  </joint>

  <!-- Shoulder -->
  <xacro:macro name="arm_link" params="name size mass parent origin axis lower upper effort velocity">
    <link name="${name}">
      <visual><geometry><box size="${size}"/></geometry><material name="orange"/></visual>
      <collision><geometry><box size="${size}"/></geometry></collision>
      <inertial><mass value="${mass}"/></inertial>
    </link>
    <joint name="${name}_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin xyz="${origin}" rpy="0 0 0"/>
      <axis xyz="${axis}"/>
      <limit lower="${lower}" upper="${upper}" effort="${effort}" velocity="${velocity}"/>
    </joint>
  </xacro:macro>

  <xacro:arm_link name="arm_link1" size="0.08 0.08 0.3" mass="1.5" parent="arm_base"
                  origin="0 0 0.2" axis="0 1 0" lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  <xacro:arm_link name="arm_link2" size="0.06 0.06 0.25" mass="1.0" parent="arm_link1"
                  origin="0 0 0.15" axis="0 1 0" lower="-1.57" upper="1.57" effort="30" velocity="1.0"/>

  <!-- Wrist -->
  <link name="gripper_base">
    <visual><geometry><box size="0.1 0.08 0.05"/></geometry><material name="gray"/></visual>
    <collision><geometry><box size="0.1 0.08 0.05"/></geometry></collision>
  </link>

  <joint name="wrist_joint" type="revolute">
    <parent link="arm_link2"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 0.15"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>

  <!-- Gripper Fingers -->
  <xacro:macro name="gripper_finger" params="name parent xyz limit_lower limit_upper">
    <link name="${name}">
      <visual><geometry><box size="0.02 0.06 0.1"/></geometry><material name="gray"/></visual>
      <collision><geometry><box size="0.02 0.06 0.1"/></geometry></collision>
    </link>
    <joint name="${name}_joint" type="prismatic">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${limit_lower}" upper="${limit_upper}" effort="10" velocity="0.1"/>
    </joint>
  </xacro:macro>

  <xacro:gripper_finger name="left_finger" parent="gripper_base" xyz="0 0.03 0.05" limit_lower="0.0" limit_upper="0.04"/>
  <xacro:gripper_finger name="right_finger" parent="gripper_base" xyz="0 -0.03 0.05" limit_lower="-0.04" limit_upper="0.0"/>

  <!-- ====================== -->
  <!-- Camera -->
  <!-- ====================== -->
  <link name="camera_link">
    <visual><geometry><box size="0.05 0.1 0.05"/></geometry><material name="red"/></visual>
    <collision><geometry><box size="0.05 0.1 0.05"/></geometry></collision>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.3 0 0.15" rpy="0 0.3 0"/>
  </joint>

  <!-- ====================== -->
  <!-- Gazebo Plugins -->
  <!-- ====================== -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image><width>640</width><height>480</height><format>R8G8B8</format></image>
        <clip><near>0.02</near><far>300</far></clip>
      </camera>
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <topic>camera/image_raw</topic>
    </sensor>
  </gazebo>

  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>shoulder_joint</joint_name>
      <joint_name>elbow_joint</joint_name>
      <joint_name>wrist_joint</joint_name>
      <joint_name>left_finger_joint</joint_name>
      <joint_name>right_finger_joint</joint_name>
    </plugin>
  </gazebo>

</robot>
