<?xml version="1.0"?>
<!-- ===================================================================
     SmartSort Warehouse Robot - FIXED Xacro Model
     Compatible with ROS2 Jazzy + Gazebo Harmonic
     =================================================================== -->

<robot name="smartsort_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ====================== -->
  <!-- Xacro Arguments        -->
  <!-- ====================== -->
  <xacro:arg name="is_ignition" default="true"/>
  <xacro:arg name="wheel_radius" default="0.15"/>
  <xacro:arg name="wheel_separation" default="0.45"/>
  <xacro:arg name="base_length" default="0.6"/>
  <xacro:arg name="base_width" default="0.4"/>
  <xacro:arg name="base_height" default="0.2"/>

  <xacro:property name="base_length" value="$(arg base_length)" />
  <xacro:property name="base_width" value="$(arg base_width)" />
  <xacro:property name="base_height" value="$(arg base_height)" />
  <xacro:property name="wheel_radius" value="$(arg wheel_radius)" />
  <xacro:property name="wheel_separation" value="$(arg wheel_separation)" />
  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Include Gazebo & ROS2 Control Submodules -->
  <xacro:include filename="$(find smartsort_robot)/urdf/smartsort_gazebo.xacro"/>
  <xacro:include filename="$(find smartsort_robot)/urdf/smartsort_ros2_control.xacro"/>

  <!-- ====================== -->
  <!-- Materials              -->
  <!-- ====================== -->
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <!-- ====================== -->
  <!-- Base Footprint (for navigation) -->
  <!-- ====================== -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ====================== -->
  <!-- Base Link -->
  <!-- ====================== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="15.0"/>
      <inertia ixx="0.2" ixy="0.0" ixz="0.0"
               iyy="0.6" iyz="0.0" izz="0.65"/>
    </inertial>
  </link>

  <!-- ====================== -->
  <!-- Left Wheel -->
  <!-- ====================== -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.0052" ixy="0.0" ixz="0.0"
               iyy="0.0052" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${-base_length/4} ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- ====================== -->
  <!-- Right Wheel -->
  <!-- ====================== -->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.0052" ixy="0.0" ixz="0.0"
               iyy="0.0052" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${-base_length/4} ${-wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- ====================== -->
  <!-- Caster Wheel -->
  <!-- ====================== -->
  <link name="caster">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.0</mu>
            <mu2>0.0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
               iyy="0.0005" iyz="0.0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${base_length/3} 0 ${-base_height/2 - 0.025}" rpy="0 0 0"/>
  </joint>

  <!-- ====================== -->
  <!-- Arm Base -->
  <!-- ====================== -->
  <link name="arm_base_link">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.08" length="0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.08" length="0.1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.0033" ixy="0.0" ixz="0.0"
               iyy="0.0033" iyz="0.0" izz="0.0064"/>
    </inertial>
  </link>

  <joint name="arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="${base_length/6} 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ====================== -->
  <!-- Shoulder Link -->
  <!-- ====================== -->
  <link name="shoulder_link">
    <visual>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.3"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.3"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="0.01125" ixy="0.0" ixz="0.0"
               iyy="0.01125" iyz="0.0" izz="0.0016"/>
    </inertial>
  </link>

  <joint name="shoulder_joint" type="revolute">
    <parent link="arm_base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-PI/2}" upper="${PI/2}" effort="50" velocity="1.0"/>
    <dynamics damping="1.0" friction="0.5"/>
  </joint>

  <!-- ====================== -->
  <!-- Elbow Link -->
  <!-- ====================== -->
  <link name="elbow_link">
    <visual>
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.25"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.25"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.0052" ixy="0.0" ixz="0.0"
               iyy="0.0052" iyz="0.0" izz="0.0006"/>
    </inertial>
  </link>

  <joint name="elbow_joint" type="revolute">
    <parent link="shoulder_link"/>
    <child link="elbow_link"/>
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-PI/2}" upper="${PI/2}" effort="30" velocity="1.0"/>
    <dynamics damping="0.7" friction="0.3"/>
  </joint>

  <!-- ====================== -->
  <!-- Gripper Base (Wrist) -->
  <!-- ====================== -->
  <link name="gripper_base_link">
    <visual>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.08 0.05"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.08 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="wrist_joint" type="revolute">
    <parent link="elbow_link"/>
    <child link="gripper_base_link"/>
    <origin xyz="0 0 0.25" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-PI/2}" upper="${PI/2}" effort="10" velocity="1.0"/>
    <dynamics damping="0.5" friction="0.2"/>
  </joint>

  <!-- ====================== -->
  <!-- Left Gripper Finger -->
  <!-- ====================== -->
  <link name="left_finger">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.06 0.1"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.06 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.00009" ixy="0.0" ixz="0.0"
               iyy="0.00009" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="left_finger"/>
    <origin xyz="0 0.03 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="0.04" effort="10" velocity="0.1"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <!-- ====================== -->
  <!-- Right Gripper Finger -->
  <!-- ====================== -->
  <link name="right_finger">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.06 0.1"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.06 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.00009" ixy="0.0" ixz="0.0"
               iyy="0.00009" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="right_finger"/>
    <origin xyz="0 -0.03 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.04" upper="0.0" effort="10" velocity="0.1"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <!-- ====================== -->
  <!-- Camera -->
  <!-- ====================== -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.1 0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.1 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.00023" ixy="0.0" ixz="0.0"
               iyy="0.00007" iyz="0.0" izz="0.00023"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_length/2 - 0.025} 0 ${base_height/2 + 0.025}" rpy="0 0.3 0"/>
  </joint>

  <!-- Camera Optical Frame -->
  <link name="camera_link_optical"/>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
  </joint>

  <!-- ====================== -->
  <!-- Gazebo-specific settings -->
  <!-- ====================== -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
  </gazebo>

  <gazebo reference="caster">
    <material>Gazebo/Grey</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <!-- ====================== -->
  <!-- Camera Sensor Plugin -->
  <!-- ====================== -->
  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <topic>camera/image_raw</topic>
    </sensor>
  </gazebo>

  <!-- ====================== -->
  <!-- Joint State Publisher Plugin -->
  <!-- ====================== -->
  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" 
            name="gz::sim::systems::JointStatePublisher">
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>shoulder_joint</joint_name>
      <joint_name>elbow_joint</joint_name>
      <joint_name>wrist_joint</joint_name>
      <joint_name>left_finger_joint</joint_name>
      <joint_name>right_finger_joint</joint_name>
      <update_rate>50</update_rate>
    </plugin>
  </gazebo>

</robot>